name: to_words
description: A Dart library to convert numbers to words. A port of the to-words JavaScript library.
version: 0.1.0
repository: https://github.com/Elvril/to-words

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0