name: to_words
description: A Dart port of the popular `to-words` JavaScript library for converting numbers (including decimals) into words with multi-locale and currency support.
version: 0.2.1
repository: https://github.com/Elvril/to_words

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0